version: '3'
services:
  mqtt-server: # Only required for MQTT based communication
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    ports: #likely to be required for developement. Likely that it can be removed in production
      - 1883:1883
      - 9001:9001
    volumes:
      - ./../src/mqtt_broker/:/mosquitto/config/
      # - ./log/:/mosquitto/log/
    networks:
      - network
  # parameter-server:
  #   build: 
  #     context: ./../src/parameter_server/
  #   restart: unless-stopped
  #   depends_on:
  #     - mqtt-server
  #   networks:
  #     - network
  #   environment:
  #     - mqtt_host=mqtt-server
  # node_1:
  #   build: 
  #     context: ./../src/node/
  #   restart: unless-stopped
  #   depends_on:
  #     - mqtt-server
  #     - parameter-server
  #   networks:
  #     - network
  #   environment:
  #     - mqtt_host=mqtt-server

networks:
  network: